### ISSUE TITLE
Unable to assing [undefined] to QQuickItem*

### ISSUE THREAD

**Issue by maxnoe** [Keyitdev/sddm-astronaut-theme#14]
Thanks for sharing this nice theme!

Running it in test-mode, I see the following error, not sure if it has an effect or not:

```
Components/SystemButtons.qml:52:13: Unable to assign [undefined] to QQuickItem*
```

**Comment by Keyitdev** [comment]
This error occurs because you can't display system buttons in test mode 
(`sddm-greeter-qt6 --test-mode --theme /usr/share/sddm/themes/sddm-astronaut-theme/`).
From https://wiki.archlinux.org/title/SDDM#Testing_(previewing)_a_theme
"Note: This is just a preview. In this mode, some actions like shutdown, suspend or login will have no effect."


You can try another way to test the theme:
`sddm --test-mode`  
In this mode, the system buttons should appear, but this mode uses [Xephyr](https://wiki.archlinux.org/title/Xephyr).


Btw I'm currently changing a lot of things (in the master branch, which I shouldn't do), so there may be some errors.

**Comment by maxnoe** [comment]
Ok, thanks for the quick response 👍
